#!/usr/bin/env python3
"""Compile Agent Registry into OpenCode Desktop agent definitions (TD-A1, Фаза 1).

Вход (authoritative sources):
  - agents/*.md            — исходные роли (frontmatter + тело-промпт)
  - runtime/model_bindings.json — override «агент -> model» (приоритетнее frontmatter)
  - config/routes_authority.json — route.agent / route.agent_hint

Выход (generated, do-not-edit):
  - .opencode/agent/<name>.md        — по одной роли на запись реестра;
    frontmatter as-is (с экранированием проблемных скаляров), model: из bindings,
    footer с route-hint'ами для оркестраторов
  - .opencode/agent/_registry_index.json — манифест поставки (agent names,
    policy_hash, source_hashes) для кросс-валидации компилятором runtime

Детерминизм: stdlib-only, сортированные ключи, стабильный YAML-emitter.
Fail-loud: ошибки валидации реестра или битые route->agent ссылки прерывают
генерацию с кодом возврата != 0 (никаких тихих пропусков).

CLI:
  python3 scripts/agent_gen/compile_agents.py            # записать артефакты
  python3 scripts/agent_gen/compile_agents.py --check    # проверить актуальность
  python3 scripts/agent_gen/compile_agents.py --print NAME [--out DIR]
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from runtime.registry import AgentRecord, AgentRegistry, FM_BLOCK_RE  # noqa: E402

AGENT_DIR_REL = ".opencode/agent"
INDEX_NAME = "_registry_index.json"
GENERATED_NOTE = "Generated by scripts/agent_gen/compile_agents.py — do not edit."


# ------------------------------------------------------------- yaml emitter
# Минималистичный детерминированный эмиттер подмножества YAML (frontmatter
# OpenCode: scalars / nested maps / simple lists). Кавычки добавляются только
# когда скаляр иначе был бы неверно прочитан (двоеточие+пробел, спецсимволы).

_PLAIN_UNSAFE_FIRST = set("-?:,[]{}#&*!|>'\"%@`")


def _needs_quotes(s: str) -> bool:
    if s == "" or s.strip() != s:
        return True
    if s[0] in _PLAIN_UNSAFE_FIRST:
        return True
    if ": " in s or s.endswith(":") or " #" in s:
        return True
    if "\n" in s or "\t" in s:
        return True
    low = s.lower()
    if low in ("true", "false", "null", "yes", "no", "on", "off", "~"):
        return True
    if re.fullmatch(r"[-+]?\d+(\.\d+)?", s):
        return True
    return False


def _scalar(v: Any) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if v is None:
        return "null"
    if isinstance(v, (int, float)):
        return repr(v)
    s = str(v)
    if _needs_quotes(s):
        esc = s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n").replace("\t", "\\t")
        return f'"{esc}"'
    return s


def emit_frontmatter(fm: dict) -> str:
    lines: list[str] = []

    def emit_map(d: dict, indent: int) -> None:
        pad = "  " * indent
        for k, v in d.items():
            if isinstance(v, dict):
                lines.append(f"{pad}{k}:")
                emit_map(v, indent + 1)
            elif isinstance(v, list):
                if not v:
                    lines.append(f"{pad}{k}: []")
                    continue
                lines.append(f"{pad}{k}:")
                for item in v:
                    lines.append(f"{pad}  - {_scalar(item)}")
            else:
                lines.append(f"{pad}{k}: {_scalar(v)}")

    emit_map(fm, 0)
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------- record -> md

FM_FIELD_ORDER = ("name", "description", "mode", "model", "temperature",
                  "steps", "hidden", "disable", "permission")


def _coerce_fm_scalars(v: Any) -> Any:
    """Нормализовать строки из fallback-парсера к YAML-типам (steps '40' -> 40,
    hidden 'true' -> True). Нужно, чтобы сгенерированный frontmatter был
    идентичен источнику после round-trip через строгий YAML-парсер."""
    if isinstance(v, dict):
        return {k: _coerce_fm_scalars(x) for k, x in v.items()}
    if isinstance(v, list):
        return [_coerce_fm_scalars(x) for x in v]
    if isinstance(v, str):
        s = v.strip()
        if re.fullmatch(r"[-+]?\d+", s):
            return int(s)
        if re.fullmatch(r"[-+]?\d*\.\d+", s):
            return float(s)
        low = s.lower()
        if low in ("true", "false"):
            return low == "true"
    return v


def ordered_frontmatter(rec: AgentRecord, *, model_override: str | None) -> dict:
    """Frontmatter записи as-is, но с каноническим порядком ключей и model из bindings."""
    raw = _coerce_fm_scalars(rec.raw_frontmatter)
    fm: dict = {}
    for key in FM_FIELD_ORDER:
        if key in raw:
            fm[key] = raw[key]
    for key in sorted(k for k in raw if k not in FM_FIELD_ORDER):
        fm[key] = raw[key]
    if model_override:
        fm["model"] = model_override
    elif "model" in fm and fm["model"] is None:
        del fm["model"]
    return fm


def render_agent_md(rec: AgentRecord, route_hints: list[tuple[str, str]]) -> str:
    fm = ordered_frontmatter(rec, model_override=rec.bound_model)
    parts = ["---\n", emit_frontmatter(fm), "---\n", rec.body.rstrip("\n"), "\n"]
    if route_hints:
        parts.append("\n<!-- GENERATED ROUTE HINTS (do not edit)\n")
        for rid, hint in route_hints:
            parts.append(f"route {rid}: {hint}\n")
        parts.append("-->\n")
    return "".join(parts)


# ------------------------------------------------------------------ pipeline

def load_route_agent_links(root: Path) -> tuple[dict[str, list[tuple[str, str]]], dict]:
    """route_id -> [(route_id, agent_hint)] per agent; возвращает также authority."""
    path = root / "config" / "routes_authority.json"
    authority = json.loads(path.read_text(encoding="utf-8"))
    hints_by_agent: dict[str, list[tuple[str, str]]] = {}
    for rid, r in sorted(authority.get("routes", {}).items()):
        agent = r.get("agent")
        if not agent:
            continue
        hints_by_agent.setdefault(agent, []).append((rid, r.get("agent_hint", "")))
    return hints_by_agent, authority


def compile_agents(root: Path, write: bool = True) -> dict:
    root = root or ROOT
    reg = AgentRegistry.load(root)
    errors = reg.validate()
    if errors:
        raise ValueError("agent registry validation failed:\n- " + "\n- ".join(errors))

    hints_by_agent, routes_authority = load_route_agent_links(root)

    # Loud-fail: каждый route.agent обязан существовать в реестре.
    unknown = sorted({a for a, links in hints_by_agent.items()
                      if a not in reg.records})
    if unknown:
        refs = [f"{a} <- {rid}" for a in unknown for rid, _ in hints_by_agent[a]]
        raise ValueError("routes reference unknown agents: " + "; ".join(refs))

    out_dir = root / AGENT_DIR_REL
    payloads: dict[str, str] = {}
    for name in sorted(reg.records):
        rec = reg.records[name]
        payloads[f"{name}.md"] = render_agent_md(rec, hints_by_agent.get(name, []))

    snapshot_path = root / "config" / "runtime_snapshot.json"
    policy_hash = None
    if snapshot_path.exists():
        try:
            policy_hash = json.loads(snapshot_path.read_text(encoding="utf-8")).get("policy_hash")
        except json.JSONDecodeError:
            pass

    index = {
        "version": 1,
        "generated": True,
        "note": GENERATED_NOTE,
        "agents": sorted(reg.records),
        "primary": sorted(r.name for r in reg.by_mode("primary")),
        "subagent": sorted(r.name for r in reg.by_mode("subagent")),
        "with_bound_model": sorted(n for n, r in reg.records.items() if r.bound_model),
        "route_agents": {rid: r.get("agent") for rid, r in sorted(routes_authority.get("routes", {}).items())},
        "policy_hash": policy_hash,
        "content_hash": hashlib.sha256(
            json.dumps(payloads, ensure_ascii=False, sort_keys=True).encode("utf-8")
        ).hexdigest(),
    }
    payloads[INDEX_NAME] = json.dumps(index, ensure_ascii=False, indent=2) + "\n"

    stale: list[str] = []
    if write:
        out_dir.mkdir(parents=True, exist_ok=True)
    else:
        for fname, content in payloads.items():
            p = out_dir / fname
            if not p.exists() or p.read_text(encoding="utf-8") != content:
                stale.append(fname)
    if write:
        for fname, content in payloads.items():
            (out_dir / fname).write_text(content, encoding="utf-8")
    return {"index": index, "stale": stale, "count": len(payloads) - 1}


# ------------------------------------------------------------------- CLI

def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true",
                    help="verify generated artifacts are current without rewriting")
    ap.add_argument("--print", dest="print_name", metavar="NAME",
                    help="render one agent to stdout (or --out dir) without writing the set")
    ap.add_argument("--out", type=Path, default=None,
                    help="output dir for --print (default: stdout)")
    args = ap.parse_args(argv)

    try:
        if args.print_name:
            reg = AgentRegistry.load(ROOT)
            errors = reg.validate()
            if errors:
                print("registry invalid:\n- " + "\n- ".join(errors), file=sys.stderr)
                return 2
            if args.print_name not in reg.records:
                print(f"unknown agent: {args.print_name!r}; known: {', '.join(reg.names())}",
                      file=sys.stderr)
                return 2
            hints_by_agent, _ = load_route_agent_links(ROOT)
            md = render_agent_md(reg.records[args.print_name],
                                 hints_by_agent.get(args.print_name, []))
            if args.out:
                args.out.mkdir(parents=True, exist_ok=True)
                (args.out / f"{args.print_name}.md").write_text(md, encoding="utf-8")
            else:
                sys.stdout.write(md)
            return 0

        result = compile_agents(ROOT, write=not args.check)
    except (ValueError, FileNotFoundError, json.JSONDecodeError) as e:
        print(json.dumps({"ok": False, "error": str(e)}, ensure_ascii=False), file=sys.stderr)
        return 2

    if args.check and result["stale"]:
        print(json.dumps({"ok": False, "error": "agent_artifacts_stale",
                          "stale": result["stale"]}, ensure_ascii=False))
        return 3
    print(json.dumps({"ok": True, "agents": result["count"],
                      "mode": "check" if args.check else "write",
                      "content_hash": result["index"]["content_hash"]},
                     ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
