#!/usr/bin/env python3
"""Install the Harness native OpenCode plugin into a project/global plugin directory.

Standard OpenCode mechanism: a .ts file in .opencode/plugins/ is auto-discovered.
The entry re-exports the compiled package entry (dist/index.js) via a relative
path so module resolution (internal bridge/host modules + node_modules) works
from the installed location.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


def harness_root() -> Path:
    env = __import__("os").environ.get("OPENCODE_HARNESS_ROOT")
    if env:
        return Path(env)
    return Path(__file__).resolve().parents[3]


def _plugin_dir(target: str, root: Path) -> Path:
    if target == "project":
        return root / ".opencode" / "plugins"
    if target == "global":
        return Path.home() / ".config" / "opencode" / "plugins"
    raise ValueError(f"unknown target: {target}")


def _relative_entry(dest_dir: Path, root: Path) -> str:
    # From <root>/.opencode/plugins/ -> <root>/packages/opencode-harness-plugin/dist/index.js
    dist_entry = root / "packages" / "opencode-harness-plugin" / "dist" / "index.js"
    if not dist_entry.is_file():
        print(f"ERROR: compiled entry not found: {dist_entry}; run `npm run build` first", file=sys.stderr)
        sys.exit(2)
    rel = Path(__import__("os").path.relpath(dist_entry, dest_dir)).as_posix()
    if not rel.startswith("."):
        rel = "./" + rel
    return rel


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--target", choices=["project", "global"], default="project")
    ap.add_argument("--report", default=None, help="path to write install report JSON")
    args = ap.parse_args()

    root = harness_root()
    dest_dir = _plugin_dir(args.target, root)
    dest_dir.mkdir(parents=True, exist_ok=True)
    dest = dest_dir / "opencode-harness-plugin.ts"
    rel = _relative_entry(dest_dir, root)
    # Windows backslashes in the relative path must be escaped in the TS string.
    rel_ts = rel.replace("\\", "/")
    dest.write_text(
        f'// Generated by install_plugin.py. Re-exports the compiled Harness plugin package.\n'
        f'export {{ default }} from "{rel_ts}"\n',
        encoding="utf-8",
    )

    report = {
        "schema": "harness-opencode-plugin-install/1.0",
        "target": args.target,
        "entry": str(dest),
        "re_exports": rel_ts,
        "mechanism": "opencode plugin auto-discovery (.opencode/plugins) -> dist/index.js",
        "no_api_keys_touched": True,
    }
    text = json.dumps(report, ensure_ascii=False, indent=2)
    if args.report:
        Path(args.report).write_text(text + "\n", encoding="utf-8")
    print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())