"""
JSON-схемы входа и выхода Генератора.
Стабильная структура для миграции лайт → комбайн.
"""

from dataclasses import dataclass, field, asdict
from typing import List, Dict, Any, Optional
import json


@dataclass
class GeneratorInput:
    """Входные данные для Генератора"""
    task_id: str                              # UUID задачи из канбана
    task_query: str                           # Исходный запрос пользователя
    context: Dict[str, Any]                   # Контекст задачи
    iteration: int                            # Номер итерации (0, 1, 2, ...)
    mode: str                                 # sufficiency | optimality
    triz_memory: Dict[str, Any]               # Принципы + матрица (от Провизора)
    ariz_memory: Dict[str, Any]               # 8 шагов АРИЗ (от Провизора)
    previous_critique: Optional[Dict[str, Any]] = None  # Критика для rework
    previous_concepts: Optional[List[Dict[str, Any]]] = None  # Предыдущие концепции

    def to_json(self) -> str:
        """Сериализация в JSON"""
        data = {
            "task_id": self.task_id,
            "task_query": self.task_query,
            "context": self.context,
            "iteration": self.iteration,
            "mode": self.mode,
            "triz_memory": self._serialize_triz_memory(self.triz_memory),
            "ariz_memory": self.ariz_memory,
            "previous_critique": self.previous_critique,
            "previous_concepts": self.previous_concepts,
        }
        return json.dumps(data, ensure_ascii=False, indent=2)

    @staticmethod
    def _serialize_triz_memory(triz_memory: Dict[str, Any]) -> Dict[str, Any]:
        """Преобразование TRIZ_MEMORY с tuple-ключами в JSON-совместимый dict"""
        matrix = triz_memory.get("contradiction_matrix", {})
        serializable_matrix = {}
        for k, v in matrix.items():
            if isinstance(k, tuple):
                serializable_matrix[f"{k[0]}|{k[1]}"] = v
            else:
                serializable_matrix[k] = v

        principles = triz_memory.get("principles", {})
        serializable_principles = {
            str(k): v for k, v in principles.items()
        }

        fallback = triz_memory.get("generic_fallback", {})

        return {
            "principles": serializable_principles,
            "contradiction_matrix": serializable_matrix,
            "generic_fallback": fallback,
            "ikr_templates": triz_memory.get("ikr_templates", []),
            "resource_types": triz_memory.get("resource_types", {}),
        }

    @classmethod
    def from_json(cls, json_str: str) -> 'GeneratorInput':
        """Десериализация из JSON"""
        data = json.loads(json_str)
        return cls(**data)


@dataclass
class Source:
    """Источник информации (литература, данные)"""
    title: str
    doi: Optional[str] = None
    url: Optional[str] = None
    verified: bool = False                    # ВСЕГДА false в лайт-версии
    verification_note: str = "Generated by LLM, not verified against real database"

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class Contradiction:
    """Противоречие (техническое или физическое)"""
    id: str                                   # contr_001, contr_002, ...
    contradiction_type: str                   # technical | physical
    improving_parameter: str
    worsening_parameter: str
    description: str

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class VepolModel:
    """Вепольная модель (nullable в лайт-версии)"""
    s1: Optional[Dict[str, Any]] = None       # Первое вещество
    s2: Optional[Dict[str, Any]] = None       # Второе вещество
    field: Optional[Dict[str, Any]] = None    # Поле
    model_type: Optional[str] = None          # Тип модели
    transformation: Optional[str] = None      # Преобразование

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class LinearizationStep:
    """Шаг линеаризации концепции"""
    id: str                                   # step_001, step_002, ...
    title: str
    description: str
    required_skills: List[str] = field(default_factory=list)
    dependencies: List[str] = field(default_factory=list)
    success_criteria: str = ""
    failure_handling: str = ""
    estimated_time_sec: float = 0.0

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class Concept:
    """Концепция решения"""
    id: str                                   # concept_001, concept_002, ...
    name: str
    description: str
    resolved_contradictions: List[str] = field(default_factory=list)  # IDs
    triz_principles_used: List[int] = field(default_factory=list)     # Номера приёмов
    linearization: List[LinearizationStep] = field(default_factory=list)
    estimated_metrics: Dict[str, Any] = field(default_factory=dict)
    # estimated_metrics: {
    #   "idealness": float (0-10),
    #   "feasibility": float (0-10),
    #   "cost_rub": float,
    #   "time_days": float
    # }

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "name": self.name,
            "description": self.description,
            "resolved_contradictions": self.resolved_contradictions,
            "triz_principles_used": self.triz_principles_used,
            "linearization": [step.to_dict() for step in self.linearization],
            "estimated_metrics": self.estimated_metrics,
        }


@dataclass
class GeneratorOutput:
    """Выход Генератора — результат выполнения АРИЗ"""
    task_id: str

    # Шаги АРИЗ (промежуточные результаты)
    task_model: Optional[Dict[str, Any]] = None
    enhanced_model: Optional[Dict[str, Any]] = None
    conflicting_pairs: Optional[List[Dict[str, Any]]] = None
    ikr: Optional[str] = None
    technical_contradictions: Optional[List[Dict[str, Any]]] = None
    physical_contradictions: Optional[List[Dict[str, Any]]] = None
    operational_zone: Optional[Dict[str, Any]] = None
    operational_time: Optional[str] = None
    resources: Optional[Dict[str, Any]] = None
    raw_solutions: Optional[List[Dict[str, Any]]] = None

    # Финальные концепции
    concepts: List[Concept] = field(default_factory=list)

    # Метаданные
    contradictions_resolved: List[Contradiction] = field(default_factory=list)
    sources: List[Source] = field(default_factory=list)
    vepol_model: VepolModel = field(default_factory=VepolModel)  # Nullable в лайт

    # Статистика
    tokens_in: int = 0
    tokens_out: int = 0
    execution_time_sec: float = 0.0

    # Расширенные метаданные (feedback, decomposition, pipeline info)
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_json(self) -> str:
        """Сериализация в JSON"""
        data = {
            "task_id": self.task_id,
            "task_model": self.task_model,
            "enhanced_model": self.enhanced_model,
            "conflicting_pairs": self.conflicting_pairs,
            "ikr": self.ikr,
            "technical_contradictions": self.technical_contradictions,
            "physical_contradictions": self.physical_contradictions,
            "operational_zone": self.operational_zone,
            "operational_time": self.operational_time,
            "resources": self.resources,
            "raw_solutions": self.raw_solutions,
            "concepts": [c.to_dict() for c in self.concepts],
            "contradictions_resolved": [c.to_dict() for c in self.contradictions_resolved],
            "sources": [s.to_dict() for s in self.sources],
            "vepol_model": self.vepol_model.to_dict(),
            "tokens_in": self.tokens_in,
            "tokens_out": self.tokens_out,
            "execution_time_sec": self.execution_time_sec,
        }
        return json.dumps(data, ensure_ascii=False, indent=2)

    @classmethod
    def from_json(cls, json_str: str) -> 'GeneratorOutput':
        """Десериализация из JSON"""
        data = json.loads(json_str)

        # Восстановление Concept
        concepts = []
        for c_data in data.get("concepts", []):
            linearization = [LinearizationStep(**step) for step in c_data.get("linearization", [])]
            concept = Concept(
                id=c_data["id"],
                name=c_data["name"],
                description=c_data["description"],
                resolved_contradictions=c_data.get("resolved_contradictions", []),
                triz_principles_used=c_data.get("triz_principles_used", []),
                linearization=linearization,
                estimated_metrics=c_data.get("estimated_metrics", {}),
            )
            concepts.append(concept)
        data["concepts"] = concepts

        # Восстановление Contradiction
        contradictions = [Contradiction(**c) for c in data.get("contradictions_resolved", [])]
        data["contradictions_resolved"] = contradictions

        # Восстановление Source
        sources = [Source(**s) for s in data.get("sources", [])]
        data["sources"] = sources

        # Восстановление VepolModel
        vepol_data = data.get("vepol_model", {})
        data["vepol_model"] = VepolModel(**vepol_data)

        return cls(**data)

    def validate(self) -> List[str]:
        """Валидация выхода. Возвращает список ошибок (пустой если всё ок)."""
        errors = []

        if len(self.concepts) < 2:
            errors.append(f"Expected at least 2 concepts, got {len(self.concepts)}")

        if len(self.concepts) > 4:
            errors.append(f"Expected at most 4 concepts, got {len(self.concepts)}")

        # Проверка, что все концепции имеют линеаризацию
        for concept in self.concepts:
            if len(concept.linearization) < 3:
                errors.append(f"Concept {concept.id} has {len(concept.linearization)} steps, expected >= 3")

        # Проверка, что все источники помечены verified=false
        for source in self.sources:
            if source.verified:
                errors.append(f"Source '{source.title}' is marked as verified, but should be false in lite")

        return errors